version: '3'

services:
  ms_widgets:
    container_name: 'ms_widgets'
    build:
      context: . 
      target: "dev"
    volumes:
      - .:/app
    links:
      - widgets_db
      - rabbit_mq
    depends_on:
      - widgets_db
      - rabbit_mq
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      DATABASE_URL: postgresql://postgres:postgres@widgets_db:5432/widgets_db?schema=public

  widgets_db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - widgets_db:/var/lib/postgresql/data

  migrate_db:
    environment:
      DATABASE_URL: postgresql://postgres:postgres@widgets_db:5432/widgets_db?schema=public
    build:
      context: .
      target: "migrate_db"
    volumes:
      - ./:/app
    depends_on:
      - widgets_db

  rabbit_mq:
    container_name: ms_widget_rabbitmq
    image: rabbitmq:management
    ports:
      - 8080:15672

  padmin_widgets:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./docker-compose-presets/servers.json:/pgadmin4/servers.json
      - ./docker-compose-presets/pgpass.conf:/pgadmin4/pgpass.json
    image: dpage/pgadmin4:6.18 
    ports:
      - 5000:80
    depends_on:
      - widgets_db

volumes:
  widgets_db:
    driver: local
